# version: '3.8'

services:
  app:
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ~/.ssh:/opt/meesa/.ssh
      - ../.devcontainer/.zshrc:/opt/meesa/.zshrc
      - ..:/opt/meesa/code
    command: ["tail -f /dev/null"]

  neo4j:
    # Docker image to be used
    image: neo4j:5.22.0
    # The ports that will be accessible from outside the container - HTTP (7474) and Bolt (7687).
    ports:
      - "7474:7474"
      - "7687:7687"

    # Passes the following environment variables to the container
    environment:
      - NEO4J_AUTH=neo4j/very-cool-password

    # Simple check testing whether the port 7474 is opened.
    # If so, the instance running inside the container is considered as "healthy".
    # This status can be checked using the "doc√üker ps" command.
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider localhost:7474 || exit 1"]
